<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
        <AssemblyName>NOCameraImprovements</AssemblyName>
        <Product>NOCameraImprovements</Product>
        <Version>1.0.0</Version>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>latest</LangVersion>
        <RestoreAdditionalProjectSources>
            https://api.nuget.org/v3/index.json;
            https://nuget.bepinex.dev/v3/index.json;
            https://nuget.samboy.dev/v3/index.json
        </RestoreAdditionalProjectSources>
        <RootNamespace>NOCameraImprovements</RootNamespace>
    </PropertyGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
        <Exec Command="/home/tylerb/git/MirageStandalone/Mirage.CodeGen/bin/Release/net6.0/linux-x64/publish/Mirage.CodeGen $(TargetPath) '$(GameManagedDir)' "/>
        <Error Condition="$(ExitCode) == 1"/>
    </Target>

    <Target Name="CopyToGameFolder" AfterTargets="PostBuild">
        <Message Importance="high" Text="[Deploy] Copying woven assembly to game folders..."/>

        <MakeDir Directories="$(BepInExPluginsDir)" Condition="'$(BepInExPluginsDir)' != ''"/>
        <MakeDir Directories="$(UnityPluginsDir)" Condition="'$(UnityPluginsDir)' != ''"/>

        <Copy
                SourceFiles="$(TargetPath)"
                DestinationFiles="$(BepInExPluginsDir)\$(Product)_$(Version)$(TargetExt)"
                SkipUnchangedFiles="true"
                Condition="'$(BepInExPluginsDir)' != ''"/>

        <Copy
                SourceFiles="$(TargetPath)"
                DestinationFiles="$(UnityPluginsDir)\$(Product)$(TargetExt)"
                SkipUnchangedFiles="true"
                Condition="'$(UnityPluginsDir)' != ''"/>

        <Message Importance="high" Text="[Deploy] Success: Mod deployed to $(Product)$(TargetExt)"/>
    </Target>

    <ItemGroup>
        <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.3" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Assembly-CSharp">
            <HintPath>$(GameManagedDir)\Assembly-CSharp.dll</HintPath>
            <Publicize>true</Publicize>
        </Reference>
        <Reference Include="Assembly-CSharp-firstpass">
            <HintPath>$(GameManagedDir)\Assembly-CSharp-firstpass.dll</HintPath>
            <Publicize>true</Publicize>
        </Reference>
        <Reference Include="Mirage">
            <HintPath>$(GameManagedDir)\Mirage.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.IMGUIModule">
            <HintPath>$(GameManagedDir)\UnityEngine.IMGUIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UI">
            <HintPath>$(GameManagedDir)\UnityEngine.UI.dll</HintPath>
        </Reference>
        <Reference Include="UniTask">
            <HintPath>$(GameManagedDir)\UniTask.dll</HintPath>
        </Reference>
        <Reference Include="Unity.TextMeshPro">
            <HintPath>$(GameManagedDir)\Unity.TextMeshPro.dll</HintPath>
        </Reference>
        <Reference Include="Rewired_Core">
            <HintPath>$(GameManagedDir)\Rewired_Core.dll</HintPath>
            <Publicize>true</Publicize>
        </Reference>
        <Reference Include="0Harmony">
            <HintPath>$(GameManagedDir)\..\..\BepInEx\core\0Harmony.dll</HintPath>
        </Reference>
        <Reference Include="BepInEx">
            <HintPath>$(GameManagedDir)\..\..\BepInEx\core\BepInEx.dll</HintPath>
        </Reference>
        <Reference Include="$(GameManagedDir)\UnityEngine*.dll"/>
    </ItemGroup>

</Project>
